package exam

import "time"

var (
	ExamList = []exam_data{
		{ID: "1",
			CourseCode:    "AVCB",
			ClassCode:     "CNTT1",
			Level:         "A",
			STExam:        1,
			TotalQuestion: 20,
			Duration:      45,
			ExamDay:       time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
			Audio:         "CNTT1",
			ExamSeriesId:  1,
			Name:          "AVCB",
			TotalPart:     2,
			TotalComment:  2,
			PointReward:   2,
			NumsJoin:      30,
			CreatedAt:     time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
			Hashtag:       []string{"Listening", "Reading"},
		},
		{ID: "2",
			CourseCode:    "MMT",
			ClassCode:     "CNTT1",
			Level:         "A",
			STExam:        1,
			TotalQuestion: 20,
			Duration:      45,
			ExamDay:       time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
			Audio:         "CNTT1",
			ExamSeriesId:  1,
			Name:          "MMT",
			TotalPart:     2,
			TotalComment:  2,
			PointReward:   2,
			NumsJoin:      30,
			CreatedAt:     time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
			Hashtag:       []string{"Listening", "Reading"},
		},
		{ID: "3",
			CourseCode:    "CSDL",
			ClassCode:     "CNTT1",
			Level:         "A",
			STExam:        1,
			TotalQuestion: 20,
			Duration:      45,
			ExamDay:       time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
			Audio:         "CNTT1",
			ExamSeriesId:  1,
			Name:          "CSDL",
			TotalPart:     2,
			TotalComment:  2,
			PointReward:   2,
			NumsJoin:      30,
			CreatedAt:     time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
			Hashtag:       []string{"Listening", "Reading"},
		},
		{
			ID:            "4",
			CourseCode:    "CSDL2",
			ClassCode:     "CNTT1",
			Level:         "A",
			STExam:        1,
			TotalQuestion: 20,
			Duration:      45,
			ExamDay:       time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
			Audio:         "CNTT1",
			ExamSeriesId:  1,
			Name:          "CSDL2",
			TotalPart:     2,
			TotalComment:  2,
			PointReward:   2,
			NumsJoin:      30,
			CreatedAt:     time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
			Hashtag:       []string{"Listening", "Reading"},
		},
		{
			ID:            "5",
			CourseCode:    "CSDL3",
			ClassCode:     "CNTT1",
			Level:         "A",
			STExam:        1,
			TotalQuestion: 20,
			Duration:      45,
			ExamDay:       time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
			Audio:         "CNTT1",
			ExamSeriesId:  2,
			Name:          "CSDL3",
			TotalPart:     2,
			TotalComment:  2,
			PointReward:   2,
			NumsJoin:      30,
			CreatedAt:     time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
			Hashtag:       []string{"Listening", "Reading"},
		},
	}
	ExamTakingList = taking_exam_resp{
		Status:         200,
		ExamName:       "ETS TOEIC 2022 TEST 1",
		Audio:          "https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_ets_2022_test01.mp3",
		ExamSeriesName: "ETS 2022",
		Data:           ExamTakingData,
	}
	ExamTakingData = []exam_taking_data{
		{
			ID:   1,
			Part: "Part 1",
			SetQuestionList: []exam_taking_question_data{

				{
					ID:    1,
					Title: "",
					Audio: "https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3",
					Side: []side_data{
						{
							Seq:     1,
							Content: "<p><strong>1. M-Au</strong></p><p><strong>(A) He's parking a truck.</strong></p><p>(B) He's lifting some furniture.</p><p>(C) He's starting an engine.</p><p>(D) He's driving a car.</p>",
						},
						{
							Seq:     2,
							Content: "<p>https://study4.com/media/tez_media1/img/ets_toeic_2022_test_1_1.png</p>",
						},
					},
				},
				{
					ID:    2,
					Title: "",
					Audio: "https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3",
					Side: []side_data{
						{
							Seq:     1,
							Content: "<p><strong>1. M-Au</strong></p><p><strong>(A) He's parking a truck.</strong></p><p>(B) He's lifting some furniture.</p><p>(C) He's starting an engine.</p><p>(D) He's driving a car.</p>",
						},
						{
							Seq:     2,
							Content: "<p>https://study4.com/media/tez_media1/img/ets_toeic_2022_test_1_1.png</p>",
						},
					},
				},
				{
					ID:    3,
					Title: "",
					Audio: "https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3",
					Side: []side_data{
						{
							Seq:     3,
							Content: "<p><strong>1. M-Au</strong></p><p><strong>(A) He's parking a truck.</strong></p><p>(B) He's lifting some furniture.</p><p>(C) He's starting an engine.</p><p>(D) He's driving a car.</p>",
						},
					},
				},
			},
		},
	}
)
