package exam

import "time"

var ExamList = []exam_data{
	{ID: "1",
		CourseCode:    "AVCB",
		ClassCode:     "CNTT1",
		Level:         "A",
		STExam:        1,
		TotalQuestion: 20,
		Duration:      45,
		ExamDay:       time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
		Audio:         "CNTT1",
		ExamSeriesId:  1,
		Name:          "AVCB",
		TotalPart:     2,
		TotalComment:  2,
		PointReward:   2,
		NumsJoin:      30,
		CreatedAt:     time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
		Hashtag:       []string{"Listening", "Reading"},
	},
	{ID: "2",
		CourseCode:    "MMT",
		ClassCode:     "CNTT1",
		Level:         "A",
		STExam:        1,
		TotalQuestion: 20,
		Duration:      45,
		ExamDay:       time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
		Audio:         "CNTT1",
		ExamSeriesId:  1,
		Name:          "MMT",
		TotalPart:     2,
		TotalComment:  2,
		PointReward:   2,
		NumsJoin:      30,
		CreatedAt:     time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
		Hashtag:       []string{"Listening", "Reading"},
	},
	{ID: "3",
		CourseCode:    "CSDL",
		ClassCode:     "CNTT1",
		Level:         "A",
		STExam:        1,
		TotalQuestion: 20,
		Duration:      45,
		ExamDay:       time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
		Audio:         "CNTT1",
		ExamSeriesId:  1,
		Name:          "CSDL",
		TotalPart:     2,
		TotalComment:  2,
		PointReward:   2,
		NumsJoin:      30,
		CreatedAt:     time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
		Hashtag:       []string{"Listening", "Reading"},
	},
	{
		ID:            "4",
		CourseCode:    "CSDL2",
		ClassCode:     "CNTT1",
		Level:         "A",
		STExam:        1,
		TotalQuestion: 20,
		Duration:      45,
		ExamDay:       time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
		Audio:         "CNTT1",
		ExamSeriesId:  1,
		Name:          "CSDL2",
		TotalPart:     2,
		TotalComment:  2,
		PointReward:   2,
		NumsJoin:      30,
		CreatedAt:     time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
		Hashtag:       []string{"Listening", "Reading"},
	},
	{
		ID:            "5",
		CourseCode:    "CSDL3",
		ClassCode:     "CNTT1",
		Level:         "A",
		STExam:        1,
		TotalQuestion: 20,
		Duration:      45,
		ExamDay:       time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
		Audio:         "CNTT1",
		ExamSeriesId:  2,
		Name:          "CSDL3",
		TotalPart:     2,
		TotalComment:  2,
		PointReward:   2,
		NumsJoin:      30,
		CreatedAt:     time.Date(2023, 03, 10, 7, 15, 52, 00, time.Local),
		Hashtag:       []string{"Listening", "Reading"},
	},
}
