
USE TN_CSDLPT

CREATE PROC SP_DANGNHAP
	@TENLOGIN NVARCHAR(100)
AS
	DECLARE @UID INT
	DECLARE MANV NVARCHAR(100)
	SELECT @UID =uid, MANV = NAME FROM sys.sysusers
	WHERE sid =SUSER_SID(@TENLOGIN)

	SELECT MAGV =@MA,
		HOTEN = (SELECT HO + ' ' + TEN FROM dbo.GIAOVIEN WHERE MAGV=@MAGV),
