USE TN_CSDLPT
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create procedure [dbo].[sp_TimNV]
	  @X INT
AS
	DECLARE @MAGV VARCHAR(10), @HO nvarchar(50), @TEN nvarchar(10)
	IF  exists(select MAGV from  dbo.GIAOVIEN  where MAGV =@X)
	BEGIN
		SELECT TENCS= (SELECT TENCS FROM dbo.COSO),  HO, TEN
		FROM 



USE TN_CSDLPT
GO
CREATE VIEW [dbo].[V_DS_KHOA]
AS
	SELECT MAKH, TENKH, MACS
	FROM KHOA 

SELECT MAKH, TENKH, MACS  FROM [dbo].[V_DS_KHOA] 

USE TN_CSDLPT SELECT MAGV, HOTEN, MAKH FROM V_DS_GIANGVIEN WHERE MAGV = TH657' TOP 1