
USE TN_CSDLPT
GO
CREATE VIEW [dbo].[V_DS_GIANGVIEN]
AS
	SELECT MAGV, CONCAT(HO, ' ', TEN) as HOTEN, MAKH
	FROM GIAOVIEN 
	--WHERE NOT EXISTS( SELECT SUSER_SNAME(sid) 
	--			FROM sys.sysusers 
	--			WHERE name = CAST(MAGV AS NVARCHAR))
GO

SELECT * FROM [V_DS_GIANGVIEN]

SELECT * FROM [V_DS_GIANGVIEN_2]

SELECT * FROM [V_DS_USERNAME]