
USE TN_CSDLPT
GO
CREATE VIEW [dbo].[V_DS_GIANGVIEN]
AS
	SELECT MAGV, CONCAT(HO, ' ', TEN) as HOTEN, MAKH
	FROM GIAOVIEN 
	WHERE NOT EXISTS( SELECT SUSER_SNAME(sid) 
				FROM sys.sysusers 
				WHERE name = CAST(MAGV AS NVARCHAR))

SELECT * FROM [dbo].[V_DS_GIANGVIEN] 